<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: These are the features
### Hidden Layer: This is where the model adjusts weights and biases.
### Output Layer: This is your target.  Binary classification will have one output node, while a multi-class problem will have many as many output nodes as there are classes.
### Neuron: Neurons are a part of the hidden layer which either activate or not depending on wieghts and biases.  
### Weight: How important/predictive a feature is in classification of target
### Activation Function: The most common of these are the Sigmoid and RELU.  A nueron is activated when it hits a certain threshold and it then fires.  If it is not activated enough it will not fire.
### Node Map: A directional analysis of the flow of information in a neural network.  Arrows start at inputs and point to which nodes then send data to.  Which in turn are linked to the nodes they send data to.
### Perceptron: A perceptron is a fundamental unit of a neural network.  It has some input, a hidden layer and an output layer.  A perceptron can have multiple inputs but has only one output.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Like most of skills we have learned in Lambda, the purpose of a neural network is to build an accurate model.  The network is like a collection of nested functions where inputs are sent to the hidden layer where through iteration or backpropogation the model learns (learning in this case means figuring out the best weights and biases for each neuron) the best weights and biases for each feature.  Once the best weights and biases are determined the model can run and use the information to make a prediction of the target class.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
## this is a binary classification problem
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
## inspect our data
df.head()
## looks like if either feature is a 0 you are in the 1 class
## only if both features are 1 are you in the 0 class


x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
import numpy as np
## add a dummy column of 1's to address 0.5 outputs below
training_inputs = np.array([[0,0, 1],
                           [1, 0, 1],
                           [0, 1, 1],
                           [1,1, 1]])
training_inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [4]:
training_outputs = np.array([[1, 1, 1, 0]]).T
training_outputs

array([[1],
       [1],
       [1],
       [0]])

In [5]:
synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [6]:
## define sigmoid function to update weights
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

## need derivative of sigmoid function
def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1- sx)


In [7]:
training_inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [8]:
training_outputs

array([[1],
       [1],
       [1],
       [0]])

In [9]:
synaptic_weights

array([[ 0.32633348],
       [-0.38138585],
       [-0.05666715]])

In [10]:
for iteration in range(200000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)
print('Synaptic weights after training')
print(synaptic_weights)
print('Outputs after training')
print(outputs)

Synaptic weights after training
[[-17.84275372]
 [-17.84275372]
 [ 26.81228907]]
Outputs after training
[[1.00000000e+00]
 [9.99872788e-01]
 [9.99872788e-01]
 [1.40072075e-04]]


In [ ]:
1, 1, 1, 0

In [11]:
training_outputs

array([[1],
       [1],
       [1],
       [0]])

## BELOW IS ATTEMPT 1, I KEPT GETTING 0.5 AS OUTPUTS SO I TRIED FROM SCRATCH ABOVE

In [ ]:
## to start make random weights
## np.random.random makes floats between 0 and 1
## the 3, 1 in parenthesis means we want three of these in one column

import numpy as np
weights = 2 * np.random.random((2,1)) - 1
weights

In [ ]:
inputs = np.array([
          [0, 0],
          [1, 0],
          [0, 1],
          [1, 1]
], dtype='int64')

In [ ]:
inputs

In [ ]:
## need 2 weights for 2 features
weights

In [ ]:
## calculate weighted sum of inputs
## for this we will use dot product of inputs (features) and multiplying by weights
weighted_sum = np.dot(inputs, weights)
weighted_sum

In [ ]:
## output the activated value for the end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

In [ ]:
correct_outputs

In [ ]:
## calculate error and use it to make our model better

error = correct_outputs - activated_output
error

In [ ]:
## how to adjust the weights
adjusted = error * sigmoid_derivative(activated_output)

In [ ]:
adjusted

In [ ]:
## update the weights
## the .T transposes the matrix
weights += np.dot(inputs.T, adjusted)
weights

In [ ]:
print(inputs, weights)

In [ ]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

In [ ]:
weights = np.random.random((2,1))
weights

In [ ]:
## this code will do what we did above 100000 times
for iteration in range(100000):
  weighted_sum = np.dot(inputs, weights)
  activated_output = sigmoid(weighted_sum)
  error = correct_outputs - activated_output
  adjusted = error * sigmoid_derivative(activated_output)
  weights += np.dot(inputs.T, adjusted)

print("Weights after training")
print(weights)
print("Output after training")
print(activated_output)

In [ ]:
correct_outputs

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [13]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

normalizer = Normalizer()
features = list(diabetes)[:-1]
features

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [14]:
## get matrix of features
## we want all the rows
## and all the columns except the last one
X = diabetes.iloc[:,:-1]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [15]:
## our targets are the outcomes
y = diabetes['Outcome']

In [16]:
X.to_numpy()

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [17]:
y.to_numpy()

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [18]:
## instantiate an object of the scaler class
scaler = MinMaxScaler()

## scale all the data
X = scaler.fit_transform(X)

## make sure we didn't lose rows or columns
X.shape

(768, 8)

In [61]:
class Perceptron2(object):

    def __init__(self, no_of_inputs, threshold=100, learning_rate=0.01):
        '''no_of_inputs helps us determine how many weights we need.
        Threshold refers to the number of epochs or iterations of the task.
        Weights are initialized based on number of inputs
        '''
        self.threshold = threshold
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_inputs + 1)
           
    def predict(self, inputs):
        '''
        take the dot product of the inputs and the self.weights vector with the the first value “removed”, 
        and then add the first value of the self.weights vector to the dot product
        '''
        for _ in range(self.threshold):
            for idx, x_i in enumerate(X):
                labels = []
                summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
                for score in summation:
                    if score > 0:
                        labels.append(0)
                    else:
                        labels.append(1)
        return labels
        
    

    def train(self, training_inputs, labels):
        for _ in range(self.threshold):
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                self.weights[0] += self.learning_rate * (label - prediction)

In [62]:
p = Perceptron2(no_of_inputs=8)

In [63]:
## split our data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=14)

In [64]:
p.train(X_train, y_train)

TypeError: 'numpy.float64' object is not iterable

In [40]:
X_train

array([[0.        , 0.88944724, 0.49180328, ..., 0.51564829, 0.42442357,
        0.        ],
       [0.23529412, 0.41708543, 0.70491803, ..., 0.4366617 , 0.10204953,
        0.21666667],
       [0.        , 0.90452261, 0.73770492, ..., 0.54396423, 0.10076857,
        0.23333333],
       ...,
       [0.        , 0.51256281, 0.42622951, ..., 0.37406855, 0.        ,
        0.        ],
       [0.47058824, 0.47738693, 0.59016393, ..., 0.54843517, 0.17378309,
        0.6       ],
       [0.        , 0.59798995, 0.        , ..., 0.4828614 , 0.02690009,
        0.05      ]])

In [41]:
y_train

220    1
720    0
506    1
553    0
753    1
      ..
327    0
406    1
268    0
344    0
619    1
Name: Outcome, Length: 614, dtype: int64

In [36]:
X_test

array([[0.76470588, 0.53266332, 0.57377049, ..., 0.50968703, 0.07386849,
        0.51666667],
       [0.17647059, 0.30653266, 0.67213115, ..., 0.51266766, 0.0704526 ,
        0.41666667],
       [0.41176471, 0.75376884, 0.63934426, ..., 0.52459016, 0.26216909,
        0.55      ],
       ...,
       [0.05882353, 0.48743719, 0.52459016, ..., 0.27123696, 0.09436379,
        0.        ],
       [0.        , 0.3718593 , 0.42622951, ..., 0.414307  , 0.08155423,
        0.01666667],
       [0.29411765, 0.73869347, 0.6147541 , ..., 0.44560358, 0.15200683,
        0.11666667]])

In [35]:
p.predict([X_test])

1

In [60]:
np.dot(inputs, self.weights[1:]) + self.weights[0]

NameError: name 'self' is not defined

In [59]:
inputs = X

In [ ]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, learning_rate = 0.01, n_iters = 10):
        self.n_iters = n_iters
        self.lr = learning_rate
        self.activation_func = self._unit_step_func
        self.weights = None
        self.bias = None
    
    
    
    def _unit_step_func(self, x):
        '''this function will return 1 if x>=0 otherwise return 0'''
        return np.where(X>= 0, 1, 0)
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None
    
    def fit(self, X, y):
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        y_ = np.array([1 if i > 0 else 0 for i in y]).T

        for _ in range(self.n_iters):
            
            for idx, x_i in enumerate(X):

                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)
                
                # Perceptron update rule
                update = self.lr * (y_[idx] - y_predicted)

                self.weights += update * x_i
                self.bias += update

    
    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return y_predicted



In [ ]:
## function to check our models accuracy
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [ ]:
## use my perceptron class
p = Perceptron(learning_rate=0.01, n_iters=1000)

In [ ]:
## convert features matrix to numpy array
## X = X.to_numpy()
type(X)

In [ ]:
## y = y.to_numpy()
type(y)

In [ ]:
## split our data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=14)

In [ ]:
## fit the model
p.fit(X_train, y_train)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?