<a href="https://colab.research.google.com/github/Faraaztqureshi/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Faraaz_Qureshi_DS10_LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [11]:
import numpy as np
## create matrix of features as numpy array
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 1, 1],
              [0, 0, 0,]
              ], dtype=float)
X

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [12]:
## create target vector
y = np.array([[0],
             [1],
             [1],
              [1],
              [1],
              [0],
              [0]
              ], dtype=float)
y

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [0]:
class NeuralNetwork:
  # step 0 set up architechture
  def __init__(self):
    self.inputs = 3
    self.hiddenNodes = 2
    # self.layers
    self.outputNodes = 1
    ## the code here will make weights for the size of inputs and hidden nodes
    ## inputs to hidden 1st set of weights
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)

    ## hidden to output 2nd set of weights
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)

  def sigmoid(self, s):
    return 1 / (1 + np.exp(-s))
  
  def sigmoidPrime(self, s):
    sx = self.sigmoid(s)
    return sx * (1 - sx)

  def feed_forward(self, X):
    ''' 
    Calculate the NN inference using feed forward
    '''
    ## weighted sum
    self.hidden_sum = np.dot(X, self.weights1)
    ## activate
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    ## weighted sum of activated hidden
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    ## to get prediction
    self.activated_output = self.sigmoid(self.output_sum)

    return self.activated_output

  def backward(self, X, y, o):
    '''
    input data, labels error
    Back prop through the network
    '''
    self.o_error = y - o # error in the output (absolute error could be other things)
    ## apply derivative of sigmoid to error (tells us how much each observation is off)
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    ## we need to know how much the weights were off by
    self.z2_error = self.o_delta.dot(self.weights2.T)
    ##
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)

    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
  
  def train(self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

In [9]:
nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.51549334]
 [0.51782749]
 [0.51184598]
 [0.515112  ]
 [0.50807253]
 [0.51516683]
 [0.51172697]]
Loss: 
 0.24869834532683527
+---------EPOCH 2---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.52620612]
 [0.52704482]
 [0.52260251]
 [0.52359867]
 [0.51817361]
 [0.52402342]
 [0.52184059]]
Loss: 
 0.2477886999496309
+---------EPOCH 3---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.53463815]
 [0.53405744]
 [0.53130614]
 [0.53014065]
 [0.52652768]
 [0.53089881]
 [0.52997431]]
Loss: 
 0.24718350096023387
+---------EPOC

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [0]:
# input image dimensions
img_rows, img_cols = 28, 28

In [0]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [5]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [0]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [7]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

In [8]:
x_train.shape

(60000, 784)

### Estimating Your `net

In [0]:
class NeuralNetwork:
  # step 0 set up architechture
  def __init__(self):
    self.inputs = 784
    self.hiddenNodes = 517
    # self.layers
    self.outputNodes = 1
    ## the code here will make weights for the size of inputs and hidden nodes
    ## inputs to hidden 1st set of weights
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)

    ## hidden to output 2nd set of weights
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)

  def sigmoid(self, s):
    return 1 / (1 + np.exp(-s))
  
  def sigmoidPrime(self, s):
    sx = self.sigmoid(s)
    return sx * (1 - sx)

  def feed_forward(self, X):
    ''' 
    Calculate the NN inference using feed forward
    '''
    ## weighted sum
    self.hidden_sum = np.dot(X, self.weights1)
    ## activate
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    ## weighted sum of activated hidden
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    ## to get prediction
    self.activated_output = self.sigmoid(self.output_sum)

    return self.activated_output

  def backward(self, X, y, o):
    '''
    input data, labels error
    Back prop through the network
    '''
    self.o_error = y - o # error in the output (absolute error could be other things)
    ## apply derivative of sigmoid to error (tells us how much each observation is off)
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    ## we need to know how much the weights were off by
    self.z2_error = self.o_delta.dot(self.weights2.T)
    ##
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)

    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
  
  def train(self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)



In [13]:
# Train my 'net
nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]


ValueError: ignored

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?